# Generated by Django 3.1.3 on 2020-12-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
