# Generated by Django 3.1.3 on 2020-12-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contact2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact2',
        ),
    ]
