# Generated by Django 3.1.3 on 2020-12-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_contact2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
