# Generated by Django 3.1.3 on 2020-12-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
